gpu: "1"
multi_gpu: null

model_name: ThreeDFlow

full: True

evaluate: True
resume: True
ckpt_dir: ./pretrain_weights/

arch: ThreeDFlow
last_relu: False
allow_less_points: False

# general args
batch_size: 8
pretrain: ThreeDFlow_168_0.0636.pth 
num_points: 8192

DEVICE: cuda

dataset: flyingthings3d_flownet3d  # Kitti_Occlusion  # FlyingThings3DSubset_Occlusion
data_root: /dataset/public_dataset_nas/flownet3d/data_processed_maxcut_35_20k_2k_8192/data_processed_maxcut_35_20k_2k_8192/

data_process:
  DEPTH_THRESHOLD: 35.
  NO_CORR: True

# miscalleneous
workers: 10

is_training: False








