gpu: null
multi_gpu: 0,1,2

model_name: ThreeDFlow

full: False

arch: ThreeDFlow
last_relu: False
allow_less_points: False

# general args
batch_size: 27
epochs: 800
learning_rate: 0.001

optimizer: Adam
pretrain: null
weight_decay: 0.0001

dim: 3
num_points: 8192

DEVICE: cuda

evaluate: False

dataset: FlyingThings3DSubset_Occlusion 
data_root: /dataset/public_dataset_nas/flownet3d/data_processed_maxcut_35_20k_2k_8192/

data_process:
  DEPTH_THRESHOLD: 35.
  NO_CORR: True

# data augmentation
aug_together:
  degree_range: 0.1745329252
  shift_range: 1.
  scale_low: 0.95
  scale_high: 1.05
  jitter_sigma: 0.01
  jitter_clip: 0.00

aug_pc2:
  degree_range: 0.
  shift_range: 0.3
  jitter_sigma: 0.01
  jitter_clip: 0.00

# miscalleneous
workers: 8

is_training: True

