gpu: "0"
multi_gpu: null

model_name: ThreeDFlow

full: False

evaluate: True
resume: True
ckpt_dir: ./pretrain_weights/carla_8192/

arch: ThreeDFlow
last_relu: False
allow_less_points: False

# general args
batch_size: 8 #14
pretrain: ThreeDFlow_503_0.1197.pth
dim: 3
num_points: 8192

DEVICE: cuda

# dataset: flyingthings3d_hplflownet #FlyingThings3DSubset # Kitti
# data_root: ../../dataset
dataset: carla
data_root: /dataset/public_dataset_nas/carla_scene_flow2/ 

data_process:
  DEPTH_THRESHOLD: 35.
  NO_CORR: True

# miscalleneous
workers: 10

is_training: True








