gpu: "1"
multi_gpu: null

model_name: ThreeDFlow

full: False

evaluate: True
resume: True
ckpt_dir: ./pretrain_weights/

arch: ThreeDFlow
last_relu: False
allow_less_points: False

# general args
batch_size: 8 #14
pretrain: ThreeDFlow_980_0.0282.pth
dim: 3
num_points: 8192

DEVICE: cuda

dataset: flyingthings3d_hplflownet #FlyingThings3DSubset # Kitti
data_root: ../../dataset

data_process:
  DEPTH_THRESHOLD: 35.
  NO_CORR: True

# miscalleneous
workers: 10

is_training: True








