gpu: null #"0"
multi_gpu: "0,1,2,3,4,5,6"

model_name: PointConv

full: False

arch: PointConv
last_relu: False
allow_less_points: False

# general args
batch_size: 42
epochs: 800
learning_rate: 0.001

optimizer: Adam
pretrain: null #./pretrain_weights/carla/PointConv_498_0.5456.pth
weight_decay: 0.0001

dim: 3
num_points: 8192

DEVICE: cuda

evaluate: False

dataset: carla #FlyingThings3DSubset # FlyingThings3DSubset KITTI
#data_root: /public_dataset_nas/flownet3d/
#data_root: /public_dataset_nas/public_workspace/ActiveSceneFlow/record2022_0315_1838/rm_egoV_fg/SF/
data_root: /dataset/public_dataset_nas/carla_scene_flow2/

data_process:
  DEPTH_THRESHOLD: 100.
  NO_CORR: True

# data augmentation
aug_together:
  degree_range: 0.1745329252
  shift_range: 1.
  scale_low: 0.95
  scale_high: 1.05
  jitter_sigma: 0.01
  jitter_clip: 0.00

aug_pc2:
  degree_range: 0.
  shift_range: 0.3
  jitter_sigma: 0.01
  jitter_clip: 0.00

# miscalleneous
workers: 16








